.Dd March  3, 2019
.Dt fsapfsinfo
.Os libfsapfs
.Sh NAME
.Nm fsapfsinfo
.Nd determines information about an Apple File System (APFS)
.Sh SYNOPSIS
.Nm fsapfsinfo
.Op Fl B Ar bodyfile
.Op Fl E Ar identifier
.Op Fl f Ar file_system_index
.Op Fl F Ar path
.Op Fl F Ar path
.Op Fl o Ar offset
.Op Fl p Ar password
.Op Fl r Ar password
.Op Fl hvV
.Ar source
.Sh DESCRIPTION
.Nm fsapfsinfo
is a utility to determine information about an Apple File System (APFS)
.Pp
.Nm fsapfsinfo
is part of the
.Nm libfsapfs
package.
.Nm libfsapfs
is a library to access the Apple File System (APFS) format
.Pp
.Ar source
is the source file.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl B Ar bodyfile
output file system information as a bodyfile
.It Fl E Ar identifier
show information about a specific file system entry or "all"
.It Fl f Ar file_system_index
show information about a specific file system or "all"
.It Fl F Ar path
show information about a specific file entry path
.It Fl h
shows this help
.It Fl H
shows the file system hierarchy
.It Fl o Ar offset
specify the volume offset
.It Fl p Ar password
specify the password
.It Fl r Ar password
specify the recovery password
.It Fl v
verbose output to stderr
.It Fl V
print version
.El
.Sh ENVIRONMENT
None
.Sh FILES
None
.Sh EXAMPLES
.Bd -literal
# fsapfsinfo -H -o 20480 image.dmg
fsapfsinfo 20181214
.sp
Apple File System (APFS) information:
.sp
File system hierarchy:
/{3e0077e4-eafa-495e-a8de-016284a49b29}/
/{3e0077e4-eafa-495e-a8de-016284a49b29}/.fseventsd
.Dl        ...
.sp
.Ed
.Sh DIAGNOSTICS
Errors, verbose and debug output are printed to stderr when verbose output \-v is enabled.
Verbose and debug output are only printed when enabled at compilation.
.Sh BUGS
Please report bugs of any kind to <joachim.metz@gmail.com> or on the project website:
https://github.com/libyal/libfsapfs/
.Sh AUTHOR
These man pages were written by Joachim Metz.
.Sh COPYRIGHT
Copyright 2018, Joachim Metz <joachim.metz@gmail.com>.
This is free software; see the source for copying conditions. There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
.Sh SEE ALSO
.Xr fsapfsmount 1
