= Apple File System (APFS)
Analysis of APFS

:toc:
:toclevels: 4

:numbered!:
[abstract]
== Summary
The Apple File System (APFS) is a volume and file system mainly used on
the Apple platforms such as MacOS and iOS. APFS succeeds the Hierarchical
File System (HFS) and Core Storage (CS).  This specification is based on
publicly availble work on the format and was enhanced by analyzing test data.

This document is intended as a working document for the APFS format.

[preface]
== Document information
[cols="1,5"]
|===
| Author(s): | Joachim Metz <joachim.metz@gmail.com>
| Abstract: | This document contains information about the Apple File System (APFS).
| Classification: | Public
| Keywords: | Apple File System, APFS
|===

[preface]
== License
....
Copyright (C) 2018, Joachim Metz <joachim.metz@gmail.com>.
Permission is granted to copy, distribute and/or modify this document under the
terms of the GNU Free Documentation License, Version 1.3 or any later version
published by the Free Software Foundation; with no Invariant Sections, no
Front-Cover Texts, and no Back-Cover Texts. A copy of the license is included
in the section entitled "GNU Free Documentation License".
....

[preface]
== Revision history
[cols="1,1,1,5",options="header"]
|===
| Version | Author | Date | Comments
| 0.0.1 | J.B. Metz | September 2018 | Initial version.
|===

:numbered:
== Overview

An APFS volume consists of:

* Container superblock

[cols="1,5",options="header"]
|===
| Characteristics | Description
| Byte order | little-endian
| Date and time values | number of nanoseconds since January 1, 1970 00:00:00 UTC (POSIX epoch)
| Character strings | Unicode strings are stored in UTF-8
|===

=== Test version

The following version of programs were used to test the information within this document:

* macOS 10.13 (High Sierra)

=== Terminology

"Physical" volume, the volume in which the APFS container is stored.

"Logical" volume, the volume in which an APFS file system is stored.

== Objects

APFS uses the "object" data type to distinguish between different data types.

=== Object

The object is 32 bytes of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 8 | | Checksum (o_cksum) +
See section: <<object_checksum,Object checkum>>
| 8 | 8 | | Object identifier (oid)
| 16 | 8 | | Object version (xid)
| 24 | 4 | | Object type +
See section: <<object_types,Object types>>
| 28 | 4 | | Object subtype +
See section: <<object_subtypes,Object subtypes>>
|===

[NOTE]
Other sources refer to the object version as transaction or checkpoint
identifier.

=== [[object_checksum]]Object checksum

The checksum algorithm:

* first calculate a Fletcher-64 checksum of the object data without the checkum value and an initial value of 0
* next calculate a Fletcher-64 checksum of the object data with the checkum value and an initial value of Fletcher-64 checksum calculated in the first step

=== [[object_types]]Object types

[cols="1,1,5",options="header"]
|===
| Value | Identifier | Description
| 0x0000001 | | Container superblock
| 0x0000002 | | B-Tree root
| 0x0000003 | | B-Tree node
| 0x0000004 | | [yellow-background]*Unknown (MTree?)*
| 0x0000005 | | Space manager header
| 0x0000006 | | [yellow-background]*Unknown (CAB?)*
| 0x0000007 | | [yellow-background]*Unknown (Chunk information block? CIB)*
| 0x0000008 | | [yellow-background]*Unknown (Space manager IP?)*
| | |
| 0x000000b | | [yellow-background]*Unknown (BTreeRootPtr?)*
| 0x000000c | | Container physical map (CPM)
| 0x000000d | | Volume superblock 
| | |
| 0x0000011 | | [yellow-background]*Unknown (NR?)*
| 0x0000012 | | [yellow-background]*Unknown (NRL?)*
| | |
| 0x0000016 | | [yellow-background]*Unknown (WBC?)*
| 0x0000017 | | [yellow-background]*Unknown (WBCL?)*
| | |
| 0x4000000 | | [yellow-background]*Unknown (flag?)*
| 0x8000000 | | [yellow-background]*Unknown (flag?)*
|===

=== [[object_subtypes]]Object subtypes

The object subtype is used by specific object types such as:

* B-Tree root
* B-Tree node

[cols="1,1,5",options="header"]
|===
| Value | Identifier | Description
| 0x000000b | | [yellow-background]*Unknown (Object map?)*
| | |
| 0x000000e | | [yellow-background]*Unknown (File system?)*
|===

== The container

APFS stores volumes inside a container. The maximum number of volumes is
dependent on the size of the container. `[HANSEN17]` indicates:

[cols="1,1,1,5",options="header"]
|===
| Container size | Maximum number of volumes
| 1 GiB | 2
| 2 GiB | 4
| 5 GiB | 10
| 10 GiB | 20
| 20 GiB | 40
| 100 GiB | 100
| 12 TiB | 100
| 1.2 PiB | 100
| 7.5 EiB | 100
|===

The container consists of:
* current container superblock
* current container physical map
* [yellow-background]*backup of current container superblock?*
* one or more pairs of:
** previous version of container physical map
** previous version of container superblock
* space manager
* container object map
* reaper
* zero or more volumes

=== Container superblock

The container superblock is [yellow-background]*unknown* of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
4+| _Object_
| 0 | 8 | | Object checksum +
See section: <<object_checksum,Object checkum>>
| 8 | 8 | | Object identifier
| 16 | 8 | | Object version (xid)
| 24 | 4 | 0x80000001 | Object type +
See section: <<object_types,Object types>>
| 28 | 4 | 0x00000000 | Object subtype
4+| _Object values_
| 32 | 4 | "NXSB" | Signature (nx_magix)
| 36 | 4 | | Block size (nx_block_size)
| 40 | 8 | | Number of blocks (nx_block_count)
| 48 | 8 | | Compatible feature flags (nx_features)
| 56 | 8 | | Read-only compatible feature flags (nx_read_only_compatible_features)
| 64 | 8 | | Incompatible feature flags (nx_incompatible_features)
| 72 | 16 | | Container identifier (nx_uuid) +
Contains a UUID stored in big-endian
| 88 | 8 | | Next (available) object identifier (nx_next_oid)
| 96 | 8 | | [yellow-background]*Next (available) ??? (nx_next_xid)*
| 104 | 4 | | [yellow-background]*Number of ??? blocks (nx_xp_desc_blocks)*
| 108 | 4 | | [yellow-background]*Number of ??? blocks (nx_xp_data_blocks)*
| 112 | 8 | | [yellow-background]*??? object identifier (nx_xp_desc_base)*
| 120 | 8 | | [yellow-background]*??? object identifier (nx_xp_data_base)*
| 128 | 4 | | [yellow-background]*Unknown (nx_xp_desc_next)*
| 132 | 4 | | [yellow-background]*Unknown (nx_xp_data_next)*
| 136 | 4 | | [yellow-background]*Unknown (nx_xp_desc_index)*
| 140 | 4 | | [yellow-background]*Unknown (nx_xp_desc_len)*
| 144 | 4 | | [yellow-background]*Unknown (nx_xp_data_index)*
| 148 | 4 | | [yellow-background]*Unknown (nx_xp_data_len)*
| 152 | 8 | | Space manager object identifier (nx_spaceman_oid) +
Contains a object identifier that can be resolved in the container physical map
| 160 | 8 | | Object map block number (nx_omap_oid) +
Contains a block number relative to the start of the "physical" volume +
See section: <<object_map,Object map>>
| 168 | 8 | | Reaper object identifier (nx_reaper_oid) +
Contains a object identifier that can be resolved in the container physical map
| 176 | 4 | | [yellow-background]*Unknown (unk_B0)*
| 180 | 4 | | Number of volumes (nx_max_file_systems)
| 184 | 100 x 8 = 800 | | Array of volume object identifiers (nx_fs_oid)
| 984 | 32 x 8 = 256 | | [yellow-background]*Unknown*
| 1240 | 8 | | [yellow-background]*Unknown (nx_blocked_out_base)*
| 1248 | 8 | | [yellow-background]*Unknown (nx_blocked_out_blocks)*
| 1254 | 8 | | [yellow-background]*Unknown*
| 1262 | 8 | | [yellow-background]*Unknown*
| 1270 | 8 | | [yellow-background]*Unknown (nx_efi_jumpstart_paddr)*
| 1278 | 8 | | [yellow-background]*Unknown*
| 1286 | 8 | | [yellow-background]*Unknown*
| 1294 | 8 | | [yellow-background]*Unknown (nx_keybag_base)*
| 1302 | 8 | | [yellow-background]*Unknown (nx_keybag_blocks)*
| 1310 | 5 x 8 = 40 | | [yellow-background]*Unknown (nx_ephemeral_info)*
| 1350 | 8 | | [yellow-background]*Unknown (nx_fusion_mt_oid)*
| 1358 | 8 | | [yellow-background]*Unknown (nx_fusion_wbc_oid)*
| 1366 | 8 | | [yellow-background]*Unknown (nx_fusion_wbc_base)*
| 1374 | 8 | | [yellow-background]*Unknown (nx_fusion_wbc_blocks)*
| 1382 | ... | | [yellow-background]*Unknown (empty values)*
|===

[NOTE]
Presumably NXSB is an abbreviation of NX superblock. At this point it is
unclear what NX stands for.

=== Container physical map (CPM)

The container physical map contains a mapping between container metadata object
identifiers and their location in the volume.

The container physical map (CPM) is 4080 bytes of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
4+| _Object_
| 0 | 8 | | Object checksum +
See section: <<object_checksum,Object checkum>>
| 8 | 8 | | Object identifier
| 16 | 8 | | Object version (xid)
| 24 | 4 | 0x4000000c | Object type +
See section: <<object_types,Object types>>
| 28 | 4 | 0x00000000 | Object subtype
4+| _Object values_
| 32 | 4 | | Flags (cpm_flags)
| 36 | 4 | | Number of entries (cpm_count)
| 40 | 101 x 40 = 4040 | | Array of map entries (cpm_map) +
See sections: <<cpm_entry,Container physical map (CPM) entry>>
|===

[NOTE]
Presumably CPM is short for container physical map, though other sources
refer to this as checkpoint map.

==== [[cpm_entry]]Container physical map (CPM) entry

The Container physical map (CPM) entry entry is 40 bytes of size and consists
of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
4+| _Object_
| 0 | 4 | | (Container) object type (cpm_type)
| 4 | 4 | | (Container) object subtype (cpm_subtype)
| 8 | 4 | | Size (cpm_size) +
Contains number of bytes
| 12 | 4 | | [yellow-background]*Unknown*
| 16 | 8 | | File system object indentifier (cpm_fs_oid)
| 24 | 8 | | (Container) object identifier (cpm_oid)
| 32 | 8 | | Physical address (cpm_paddr) +
Contains a block number relative to the start of the "physical" volume
|===

=== Space manager

The space manager is [yellow-background]*unknown* of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
4+| _Object_
| 0 | 8 | | Object checksum +
See section: <<object_checksum,Object checkum>>
| 8 | 8 | | Object identifier
| 16 | 8 | | Object version (xid)
| 24 | 4 | 0x80000005 | Object type +
See section: <<object_types,Object types>>
| 28 | 4 | 0x00000000 | Object subtype
4+| _Object values_
| 32 | 4 | | Block size (block_size)
| | 4 | | Number of blocks per chunk (blocks_per_chunk)
| | 4 | | Number of chunks per CIB (chunks_per_cib)
| | 4 | | Number of CIBs per CAB (cibs_per_cab)
| | 8 | | Number of blocks (block_count)
| | 8 | | Number of chunks (chunk_count)
| | 4 | | Number of CIBs (cib_count)
| | 4 | | Number of CABs (cab_count)
| | 8 | | Number of unused blocks (free_count)
| | 8 | | [yellow-background]*Unknown (cib_arr_offs)*
| | 8 | | [yellow-background]*Unknown (cab_arr_offs?)*
| | 8 | | [yellow-background]*Unknown (tier2_block_count)*
| | 8 | | [yellow-background]*Unknown (tier2_chunk_count)*
| | 4 | | [yellow-background]*Unknown (tier2_cib_count)*
| | 4 | | [yellow-background]*Unknown (tier2_cab_count)*
| | 8 | | [yellow-background]*Unknown (tier2_free_count)*
| | 8 | | [yellow-background]*Unknown (tier2_cib_arr_offs)*
| | 8 | | [yellow-background]*Unknown (tier2_cab_arr_offs?)*
| | 4 | | [yellow-background]*Unknown*
| | 4 | | [yellow-background]*Unknown*
| | 8 | | [yellow-background]*Unknown (ip_block_count)*
| | 4 | | [yellow-background]*Unknown (ip_bm_block_count)*
| | 4 | | [yellow-background]*Unknown (ip_bitmap_block_count)*
| | 8 | | [yellow-background]*Unknown (ip_bm_base_address)*
| | 8 | | [yellow-background]*Unknown (ip_base_address)*
| | 8 | | [yellow-background]*Unknown*
| | 8 | | [yellow-background]*Unknown*
| | 8 | | [yellow-background]*Unknown (free_queue_count_1)*
| | 8 | | [yellow-background]*Unknown (free_queue_tree_1)*
| | 8 | | [yellow-background]*Unknown*
| | 8 | | [yellow-background]*Unknown*
| | 8 | | [yellow-background]*Unknown*
| | 8 | | [yellow-background]*Unknown (free_queue_count_2)*
| | 8 | | [yellow-background]*Unknown (free_queue_tree_2)*
| | 8 | | [yellow-background]*Unknown*
| | 8 | | [yellow-background]*Unknown*
| | 8 | | [yellow-background]*Unknown*
| | 8 | | [yellow-background]*Unknown (free_queue_count_3)*
| | 8 | | [yellow-background]*Unknown (free_queue_tree_3)*
| | 8 | | [yellow-background]*Unknown*
| | 8 | | [yellow-background]*Unknown*
| | 8 | | [yellow-background]*Unknown*
| | 2 | | [yellow-background]*Unknown (bitmap_next_array_free)*
| | 2 | | [yellow-background]*Unknown*
| | 4 | | [yellow-background]*Unknown*
| | 4 | | [yellow-background]*Unknown*
| | 4 | | [yellow-background]*Unknown (unk_array_offs)*
| | 4 | | [yellow-background]*Unknown*
| | 4 | | [yellow-background]*Unknown*
| | 8 | | [yellow-background]*Unknown*
| | 16 x 2 = 32 | | [yellow-background]*Unknown*
| | 8 | | [yellow-background]*Unknown (blockid_vol_bitmap_hdr)*
| | 2128 | | [yellow-background]*Unknown*
| | 8 | | [yellow-background]*Unknown*
| | 8 | | [yellow-background]*Unknown*
| | 16 x 2 = 32 | | [yellow-background]*Unknown*
| | 191 x 8 = 1528 | | [yellow-background]*Unknown (bid_bmp_hdr_list)*
| | ... | | [yellow-background]*Unknown*
|===

[NOTE]
CIB could be short for chunk indirect block

=== Reaper

The reaper is [yellow-background]*unknown* of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
4+| _Object_
| 0 | 8 | | Object checksum +
See section: <<object_checksum,Object checkum>>
| 8 | 8 | | Object identifier
| 16 | 8 | | Object version (xid)
| 24 | 4 | 0x80000011 | Object type +
See section: <<object_types,Object types>>
| 28 | 4 | 0x00000000 | Object subtype
4+| _Object values_
| 32 | 8 | | [yellow-background]*Unknown*
| | 8 | | [yellow-background]*Unknown*
| | 8 | | [yellow-background]*Unknown*
| | 8 | | [yellow-background]*Unknown*
| | 4 | | [yellow-background]*Unknown*
| | 4 | | [yellow-background]*Unknown*
| | 4 | | [yellow-background]*Unknown*
| | 4 | | [yellow-background]*Unknown*
| | 8 | | [yellow-background]*Unknown*
| | 8 | | [yellow-background]*Unknown*
| | 8 | | [yellow-background]*Unknown*
| | 4 | | [yellow-background]*Unknown*
| | 4 | | [yellow-background]*Unknown*
|===

==== Reaper list

The reaper list entry is [yellow-background]*unknown* of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
4+| _Object_
| 0 | 8 | | Object checksum +
See section: <<object_checksum,Object checkum>>
| 8 | 8 | | Object identifier
| 16 | 8 | | Object version (xid)
| 24 | 4 | 0x80000012 | Object type +
See section: <<object_types,Object types>>
| 28 | 4 | 0x00000000 | Object subtype
4+| _Object values_
| 32 | 4 | | [yellow-background]*Unknown*
| 36 | 4 | | [yellow-background]*Unknown*
| 40 | 4 | | [yellow-background]*Unknown*
| 44 | 4 | | [yellow-background]*Unknown (max_record_count)*
| 48 | 4 | | [yellow-background]*Unknown (record_count)*
| 52 | 4 | | [yellow-background]*Unknown (first_index)*
| 56 | 4 | | [yellow-background]*Unknown (last_index)*
| 60 | 4 | | [yellow-background]*Unknown (free_index)*
| 64 | 100 x ... | | Array of reaper list entries (nrle) +
See section: <<reaper_list_entry,Reaper list entry>>
|===

==== [[reaper_list_entry]]Reaper list entry

The reaper list entry is 40 bytes of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 4 | | Forward link (fwlink)
| 4 | 4 | | [yellow-background]*Unknown*
| 8 | 4 | | Type (type)
| 12 | 4 | | Block size (blksize)
| 16 | 8 | | Object identifier (oid)
| 24 | 8 | | Physical address (paddr) +
Contains a block number relative to the start of the "physical" volume
| 32 | 8 | | Object version (xid)
|===

== [[object_map]]Object map

The object map contains a mapping between volume object identifiers and their
"physical" location.

The object map consists of:

* object map (object)
* object map B-tree

=== Object map object

The object map 72 bytes of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
4+| _Object_
| 0 | 8 | | Object checksum +
See section: <<object_checksum,Object checkum>>
| 8 | 8 | | Object identifier
| 16 | 8 | | Object version (xid)
| 24 | 4 | 0x4000000b | Object type +
See section: <<object_types,Object types>>
| 28 | 4 | 0x00000000 | Object subtype
4+| _Object values_
| 32 | 4 | | [yellow-background]*Unknown*
| 36 | 4 | | [yellow-background]*Unknown*
| 40 | 4 | | [yellow-background]*Unknown (type_1)*
| 44 | 4 | | [yellow-background]*Unknown (type_2)*
| 48 | 8 | | Object map B-tree object identifier (om_tree_oid)
| 56 | 8 | | [yellow-background]*Unknown (oms_tree_oid)*
| 64 | 8 | | [yellow-background]*Unknown (oms_tree_xid)*
|===

== B-tree

A B-tree consists of:

* B-tree (root or node) object
* B-tree header
* B-tree entries
* keys data
* unused data
* values data
* B-tree footer

=== B-tree object

==== B-tree root object

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
4+| _Object_
| 0 | 8 | | Object checksum +
See section: <<object_checksum,Object checkum>>
| 8 | 8 | | Object identifier
| 16 | 8 | | Object version (xid)
| 24 | 4 | 0x40000002 | Object type +
See section: <<object_types,Object types>>
| 28 | 4 | | Object subtype +
See section: <<object_subtypes,Object subtypes>>
|===

==== B-tree node object

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
4+| _Object_
| 0 | 8 | | Object checksum +
See section: <<object_checksum,Object checkum>>
| 8 | 8 | | Object identifier
| 16 | 8 | | Object version (xid)
| 24 | 4 | 0x40000003 | Object type +
See section: <<object_types,Object types>>
| 28 | 4 | | Object subtype +
See section: <<object_subtypes,Object subtypes>>
|===

=== B-tree header

The B-tree header is stored after the B-tree root or node object.

The B-tree header is 24 bytes of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 2 | | Flags (flags) +
See section: <<btree_flags,B-tree flags>>
| 2 | 2 | | Level (level)
| 4 | 4 | | Number of keys (key_count)
| 8 | 2 | | Entries data offset (table_space_offset) +
Contains an offset relative to the end of the B-tree header
| 10 | 2 | | Entries data size (table_space_length)
| 12 | 2 | | Unused data offset (free_space_offset) +
Contains an offset relative to the end of the entries data
| 14 | 2 | | Unused data size (free_space_length)
| 16 | 2 | | [yellow-background]*Unknown (key_free_list_space_offset)* +
Contains an offset relative to ??? or -1 (0xffff) if not set
| 18 | 2 | | [yellow-background]*Unknown (key_free_list_space_length)*
| 20 | 2 | | [yellow-background]*Unknown (val_free_list_space_offset)* +
Contains an offset relative to ??? or -1 (0xffff) if not set
| 22 | 2 | | [yellow-background]*Unknown (val_free_list_space_length)*
|===

==== [[btree_flags]]B-tree flags

[cols="1,1,5",options="header"]
|===
| Value | Identifier | Description
| 0x0001 | |  [yellow-background]*Unknown*
| 0x0002 | |  [yellow-background]*Unknown*
| 0x0004 | |  [yellow-background]*Unknown (Has fixed-size B-tree entry?)*
|===

=== B-tree entries

The B-tree entries are stored after the B-tree header.

==== Fixed-size B-tree entry

The fixed-size B-tree entry is 4 bytes of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 2 | | Key data offset (key_offs) +
Contains an offset relative to the end of the entries data
| 2 | 2 | | Value data offset (value_offs) +
Contains a reversed offset relative to the startof the B-Tree footer
|===

==== Variable-size B-tree entry

The variable-size B-tree entry is 8 bytes of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 2 | | Key data offset (key_offs) +
Contains an offset relative to the end of the entries data
| 2 | 2 | | Key data size (key_len)
| 4 | 2 | | Value data offset (value_offs) +
Contains a reversed offset relative to the startof the B-Tree footer
| 6 | 2 | | Value data size (value_len)
|===

=== B-tree footer

The B-tree footer is stored at the end of the block.

The B-tree footer is 40 bytes of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 4 | | [yellow-background]*Unknown*
| 4 | 4 | | Node size (nodesize)
| 8 | 4 | | Key size (key_size) +
Set to 0 if key has a variable size
| 12 | 4 | | Value size (val_size) +
Set to 0 if value has a variable size
| 16 | 4 | | Maximum key size (key_max_size)
| 20 | 4 | | Maximum value size (val_max_size)
| 24 | 8 | | Number of entries (entries_cnt)
| 32 | 8 | | Number of nodes (nodes_cnt)
|===

=== Object map B-tree values

==== Object map B-tree key

The object map B-tree key is 16 bytes of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 8 | | Key object identifier (ok_oid)
| 8 | 8 | | Key object version (ok_xid)
|===

==== Object map B-tree value

The object map B-tree value is 16 bytes of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 4 | | Value object flags (ov_flags) +
See section: <<object_map_btree_value_flags,Object map B-tree value flags>>
| 4 | 4 | | Value object size (ov_size)
| 8 | 8 | | Value object physical addresss (ov_paddr) +
Contains a block number relative to the start of the "physical" volume
|===

===== [[object_map_btree_value_flags]]Object map B-tree value flags

[cols="1,1,5",options="header"]
|===
| Value | Identifier | Description
|===

=== File system B-tree values

==== File system B-tree key

The file system B-tree key is variable of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 60 bits | | [yellow-background]*Unknown (catalog node identifier?)*
| 7.4 | 4 bits | | Key data types +
See section: <<file_system_btree_data_types,File system B-tree data types>>
| 8 | ... | | Optional additional key data
|===

==== [[file_system_btree_data_types]]File system B-tree data types

[cols="1,1,5",options="header"]
|===
| Value | Identifier | Description
| 0x1 | | Snapshot metadata
| 0x2 | | Physical extent
| 0x3 | | Inode
| 0x4 | | Extended attribure (xattr)
| 0x5 | | Sibling link
| 0x6 | | Data stream
| 0x7 | | [yellow-background]*Unknown (Crypto state?)*
| 0x8 | | File extent
| 0x9 | | Directory record
| 0xa | | Directory size
| 0xb | | Snapshot name
| 0xc | | Sibling map
|===

==== Inode

===== Inode key data

The inode key data is 8 bytes of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 60 bits | | [yellow-background]*Unknown (catalog node identifier?)*
| 7.4 | 4 bits | 0x3 | Key data types +
|===

....
00000000: 02 00 00 00 00 00 00 30                            .......0
....

===== Inode value data

....
00000000: 01 00 00 00 00 00 00 00  02 00 00 00 00 00 00 00   ........ ........
00000010: da 41 b8 12 55 23 52 15  85 2b 71 56 55 23 52 15   .A..U#R. .+qVU#R.
00000020: 85 2b 71 56 55 23 52 15  da 41 b8 12 55 23 52 15   .+qVU#R. .A..U#R.
00000030: 00 80 00 00 00 00 00 00  01 00 00 00 00 00 00 00   ........ ........
00000040: 02 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ........ ........
00000050: fd 41 00 00 00 00 00 00  00 00 00 00 01 00 08 00   .A...... ........
00000060: 04 02 05 00 72 6f 6f 74  00 00 00 00               ....root ....
....

==== Data stream

===== Data stream key data

The data stream key data is 8 bytes of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 60 bits | | [yellow-background]*Unknown (catalog node identifier?)*
| 7.4 | 4 bits | 0x6 | Key data types +
|===

....
00000000: 11 00 00 00 00 00 00 60                            .....
....

===== Data stream value data

....
00000000: 01 00 00 00                                        ....
....

==== File extent

===== File extent key data

The file extend key data is 16 bytes of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 60 bits | | [yellow-background]*Unknown (catalog node identifier?)*
| 7.4 | 4 bits | 0x8 | Key data types +
| 8 | 8 | | [yellow-background]*Unknown*
|===

....
00000000: 11 00 00 00 00 00 00 80  00 00 00 00 00 00 00 00   ........ ........
....

===== File extent value data

....
00000000: 00 10 00 00 00 00 00 00  65 00 00 00 00 00 00 00   ........ e.......
00000010: 00 00 00 00 00 00 00 00                            ........
....

==== Directory record

===== Directory record key data

The directory record key data is variable of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 60 bits | | [yellow-background]*Unknown (catalog node identifier?)*
| 7.4 | 4 bits | 0x9 | Key data types +
| 8 | 1 | | Name string size +
Includes the size of the end-of-string character
| 9 | 4 | | [yellow-background]*Unknown (name hash?)*
| 13 | ... | | Name string +
Contains an UTF-8 encoded string with an end-of-string character
|===

....
00000000: 01 00 00 00 00 00 00 90  0c 8c a6 ac 70 72 69 76   ........ ....priv
00000010: 61 74 65 2d 64 69 72 00                            ate-dir.
....

====== Directory record value data

....
00000000: 03 00 00 00 00 00 00 00  6b 5b b8 12 55 23 52 15   ........ k[..U#R.
00000010: 04 00                                              ..
....

== Volume

The volume consists of:

* volume superblock
* volume object map
* ...

=== Volume superblock

The volume superblock is [yellow-background]*unknown* of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
4+| _Object_
| 0 | 8 | | Object checksum +
See section: <<object_checksum,Object checkum>>
| 8 | 8 | | Object identifier
| 16 | 8 | | Object version (xid)
| 24 | 4 | 0x0000000d | Object type +
See section: <<object_types,Object types>>
| 28 | 4 | 0x00000000 | Object subtype
4+| _Object values_
| 32 | 4 | "APSB" | Signature (apfs_magic)
| 36 | 4 | | [yellow-background]*Unknown (apfs_fs_index)*
| 40 | 8 | | Compatible feature flags (apfs_features
| 48 | 8 | | Read-only compatible feature flags (apfs_readonly_compatible_features)
| 56 | 8 | | Incompatible feature flags (apfs_incompatible_features) +
<<volume_superblock_feature,Volume superblock features>>
| 64 | 8 | | [yellow-background]*Unknown (apfs_unmount_time)* +
Contains the number of nanoseconds since January 1, 1970 00:00:00 UTC of 0 if not set
| 72 | 8 | | Number of reserved blocks (apfs_reserve_block_count)
| 80 | 8 | | Number of quota blocks (apfs_quota_block_count)
| 88 | 8 | | [yellow-background]*Unknown (apfs_fs_alloc_count)*
| 96 | 8 | | [yellow-background]*Unknown*
| 104 | 4 | | [yellow-background]*Unknown*
| 108 | 4 | | [yellow-background]*Unknown*
| 112 | 4 | | [yellow-background]*Unknown*
| 116 | 4 | | File system root tree object type (apfs_root_tree_type) +
See section: <<object_types,Object types>>
| 120 | 4 | | [yellow-background]*Unknown (apfs_extentref_tree_type)* +
See section: <<object_types,Object types>>
| 124 | 4 | | Snapshot metadata tree object type (apfs_snap_meta_tree_type) +
See section: <<object_types,Object types>>
| 132 | 8 | | Object map block number (apfs_omap_oid) +
Contains a block number relative to the start of the "physical" volume +
See section: <<object_map,Object map>>
| 140 | 8 | | File system root tree object identifier (apfs_root_tree_oid)
| 148 | 8 | | [yellow-background]*Unknown (apfs_extentref_tree_oid)*
| 156 | 8 | | [yellow-background]*Unknown (apfs_snap_meta_tree_oid)*
| 164 | 8 | | [yellow-background]*Unknown (apfs_revert_to_xid)*
| 172 | 8 | | [yellow-background]*Unknown*
| 180 | 8 | | [yellow-background]*Unknown (apfs_next_obj_id)*
| 188 | 8 | | [yellow-background]*Unknown (apfs_num_files)*
| 196 | 8 | | [yellow-background]*Unknown (apfs_num_directories)*
| 204 | 8 | | [yellow-background]*Unknown (apfs_num_symlinks)*
| 212 | 8 | | [yellow-background]*Unknown (apfs_num_other_fsobjects)*
| 220 | 8 | | [yellow-background]*Unknown (apfs_num_snapshots)*
| 228 | 8 | | [yellow-background]*Unknown (apfs_total_blocks_alloced)*
| 236 | 8 | | [yellow-background]*Unknown (apfs_total_blocks_freed)*
| 244 | 16 | | Volume identifier (apfs_vol_uuid) +
Contains a UUID stored in big-endian
| 260 | 8 | | [yellow-background]*Unknown (apfs_last_mod_time)* +
Contains the number of nanoseconds since January 1, 1970 00:00:00 UTC of 0 if not set
| 268 | 8 | | [yellow-background]*Unknown (apfs_fs_flags)* +
<<volume_superblock_flags,Volume superblock flags>>
| 276 | 40 | | Creation change information (apfs_formatted_by) +
See section: <<volume_superblock_change_information,Volume superblock change information>>
| 316 | 8 x 40 | | Modification change information (apfs_modified_by) +
[yellow-background]*Contains the 8 last entries from least recent to most recent?* +
See section: <<volume_superblock_change_information,Volume superblock change information>>
| 636 | 256 | | Volume name (apfs_volname)
| 892 | 4 | | [yellow-background]*Unknown (apfs_next_doc_id)*
| 896 | 4 | | [yellow-background]*Unknown*
| 900 | 8 | | [yellow-background]*Unknown*
| 908 | 32 | | [yellow-background]*Unknown*
| 940 | ... | | [yellow-background]*Unknown (Empty values)*
|===

=== [[volume_superblock_change_information]]Volume superblock change information

The volume superblock change information is 48 bytes of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 32 | | Application +
String that contains the first 31 characters of the name and version of the application that changed the file system +
Contains 0 if not set
| 32 | 8 | | Change date and time +
Contains the number of nanoseconds since January 1, 1970 00:00:00 UTC of 0 if not set
| 40 | 8 | | Change object version +
Contains 0 if not set
|===

==== [[volume_superblock_feature]]Volume superblock features

[cols="1,1,5",options="header"]
|===
| Value | Identifier | Description
| 0x00000000 | | [yellow-background]*Unknown (old format (iOS)?)*
| 0x00000001 | | [yellow-background]*Unknown (case-insensitive?)*
| 0x00000008 | | [yellow-background]*Unknown (case-sensitive?)*
|===

==== [[volume_superblock_flags]]Volume superblock flags

[cols="1,1,5",options="header"]
|===
| Value | Identifier | Description
| 0x00000000 | | [yellow-background]*Unknown (encrypted?)*
| 0x00000001 | | [yellow-background]*Unknown (unencrypted?)*
| 0x00000002 | | [yellow-background]*Unknown (effaceable?)*
|===

== Notes

....
fsck_apfs -n apfs_empty.raw
** Checking volume.
** Checking the container superblock.
** Checking the space manager.
** Checking the object map.
** Checking the APFS volume superblock.
** Checking the object map.
mount_apfs: mount: Operation not supported by device
error: mount_apfs exit status 73
** Checking the fsroot tree.
** Checking the snapshot metadata tree.
** Checking the extent ref tree.
** Checking the snapshots.
warning: unmount: /private/var/folders/7k/s4ykb4095ld38gz50kvkhf_m0000gn/T/fsck_apfs.586: Invalid argument
** Verifying allocated space.
** The volume apfs_empty.raw appears to be OK.

diskutil apfs list
APFS Container (1 found)
|
+-- Container disk4 B069A33C-65E6-4DAF-BD60-081493F91116
    ====================================================
    APFS Container Reference:     disk4
    Size (Capacity Ceiling):      1007616 B (1.0 MB)
    Minimum Size:                 1007616 B (1.0 MB)
    Capacity In Use By Volumes:   376832 B (376.8 KB) (37.4% used)
    Capacity Not Allocated:       630784 B (630.8 KB) (62.6% free)
    |
    +-< Physical Store disk3s1 D05BEA77-81B3-4A8D-A82A-BC5C7D2FB27C
    |   -----------------------------------------------------------
    |   APFS Physical Store Disk:   disk3s1
    |   Size:                       1007616 B (1.0 MB)
    |
    +-> Volume disk4s1 9428213B-2E82-49E9-871E-7220B157FC8D
        ---------------------------------------------------
        APFS Volume Disk (Role):   disk4s1 (No specific role)
        Name:                      untitled (Case-insensitive)
        Mount Point:               /Volumes/untitled
        Capacity Consumed:         24576 B (24.6 KB)
        FileVault:                 No

find /Volumes/SingleVolume
/Volumes/SingleVolume
/Volumes/SingleVolume/.fseventsd
/Volumes/SingleVolume/.fseventsd/fseventsd-uuid
/Volumes/SingleVolume/.fseventsd/0000000000793354
/Volumes/SingleVolume/.fseventsd/0000000000793353
....

....
/private-dir/
/root/
....

:numbered!:
[appendix]
== References

`[HANSEN17]`

[cols="1,5",options="header"]
|===
| Title: | Decoding the APFS file system
| Author(s): | Hansen, Kurt & Toolan, Fergus
| Date: | September 2017
| URL: | https://www.researchgate.net/publication/319573636_Decoding_the_APFS_file_system
|===

[cols="1,5",options="header"]
|===
| Title: | apfs_fuse
| Author(s): | S. Gander
| Date: | October 2017
| URL: | https://github.com/sgan81/apfs-fuse
|===

[appendix]
== GNU Free Documentation License
Version 1.3, 3 November 2008
Copyright © 2000, 2001, 2002, 2007, 2008 Free Software Foundation, Inc.
<http://fsf.org/>

Everyone is permitted to copy and distribute verbatim copies of this license
document, but changing it is not allowed.

=== 0. PREAMBLE
The purpose of this License is to make a manual, textbook, or other functional
and useful document "free" in the sense of freedom: to assure everyone the
effective freedom to copy and redistribute it, with or without modifying it,
either commercially or noncommercially. Secondarily, this License preserves for
the author and publisher a way to get credit for their work, while not being
considered responsible for modifications made by others.

This License is a kind of "copyleft", which means that derivative works of the
document must themselves be free in the same sense. It complements the GNU
General Public License, which is a copyleft license designed for free software.

We have designed this License in order to use it for manuals for free software,
because free software needs free documentation: a free program should come with
manuals providing the same freedoms that the software does. But this License is
not limited to software manuals; it can be used for any textual work,
regardless of subject matter or whether it is published as a printed book. We
recommend this License principally for works whose purpose is instruction or
reference.

=== 1. APPLICABILITY AND DEFINITIONS
This License applies to any manual or other work, in any medium, that contains
a notice placed by the copyright holder saying it can be distributed under the
terms of this License. Such a notice grants a world-wide, royalty-free license,
unlimited in duration, to use that work under the conditions stated herein. The
"Document", below, refers to any such manual or work. Any member of the public
is a licensee, and is addressed as "you". You accept the license if you copy,
modify or distribute the work in a way requiring permission under copyright law.

A "Modified Version" of the Document means any work containing the Document or
a portion of it, either copied verbatim, or with modifications and/or
translated into another language.

A "Secondary Section" is a named appendix or a front-matter section of the
Document that deals exclusively with the relationship of the publishers or
authors of the Document to the Document's overall subject (or to related
matters) and contains nothing that could fall directly within that overall
subject. (Thus, if the Document is in part a textbook of mathematics, a
Secondary Section may not explain any mathematics.) The relationship could be a
matter of historical connection with the subject or with related matters, or of
legal, commercial, philosophical, ethical or political position regarding them.

The "Invariant Sections" are certain Secondary Sections whose titles are
designated, as being those of Invariant Sections, in the notice that says that
the Document is released under this License. If a section does not fit the
above definition of Secondary then it is not allowed to be designated as
Invariant. The Document may contain zero Invariant Sections. If the Document
does not identify any Invariant Sections then there are none.

The "Cover Texts" are certain short passages of text that are listed, as
Front-Cover Texts or Back-Cover Texts, in the notice that says that the
Document is released under this License. A Front-Cover Text may be at most 5
words, and a Back-Cover Text may be at most 25 words.

A "Transparent" copy of the Document means a machine-readable copy, represented
in a format whose specification is available to the general public, that is
suitable for revising the document straightforwardly with generic text editors
or (for images composed of pixels) generic paint programs or (for drawings)
some widely available drawing editor, and that is suitable for input to text
formatters or for automatic translation to a variety of formats suitable for
input to text formatters. A copy made in an otherwise Transparent file format
whose markup, or absence of markup, has been arranged to thwart or discourage
subsequent modification by readers is not Transparent. An image format is not
Transparent if used for any substantial amount of text. A copy that is not
"Transparent" is called "Opaque".

Examples of suitable formats for Transparent copies include plain ASCII without
markup, Texinfo input format, LaTeX input format, SGML or XML using a publicly
available DTD, and standard-conforming simple HTML, PostScript or PDF designed
for human modification. Examples of transparent image formats include PNG, XCF
and JPG. Opaque formats include proprietary formats that can be read and edited
only by proprietary word processors, SGML or XML for which the DTD and/or
processing tools are not generally available, and the machine-generated HTML,
PostScript or PDF produced by some word processors for output purposes only.

The "Title Page" means, for a printed book, the title page itself, plus such
following pages as are needed to hold, legibly, the material this License
requires to appear in the title page. For works in formats which do not have
any title page as such, "Title Page" means the text near the most prominent
appearance of the work's title, preceding the beginning of the body of the text.

The "publisher" means any person or entity that distributes copies of the
Document to the public.

A section "Entitled XYZ" means a named subunit of the Document whose title
either is precisely XYZ or contains XYZ in parentheses following text that
translates XYZ in another language. (Here XYZ stands for a specific section
name mentioned below, such as "Acknowledgements", "Dedications",
"Endorsements", or "History".) To "Preserve the Title" of such a section when
you modify the Document means that it remains a section "Entitled XYZ"
according to this definition.

The Document may include Warranty Disclaimers next to the notice which states
that this License applies to the Document. These Warranty Disclaimers are
considered to be included by reference in this License, but only as regards
disclaiming warranties: any other implication that these Warranty Disclaimers
may have is void and has no effect on the meaning of this License.

=== 2. VERBATIM COPYING
You may copy and distribute the Document in any medium, either commercially or
noncommercially, provided that this License, the copyright notices, and the
license notice saying this License applies to the Document are reproduced in
all copies, and that you add no other conditions whatsoever to those of this
License. You may not use technical measures to obstruct or control the reading
or further copying of the copies you make or distribute. However, you may
accept compensation in exchange for copies. If you distribute a large enough
number of copies you must also follow the conditions in section 3.

You may also lend copies, under the same conditions stated above, and you may
publicly display copies.

=== 3. COPYING IN QUANTITY
If you publish printed copies (or copies in media that commonly have printed
covers) of the Document, numbering more than 100, and the Document's license
notice requires Cover Texts, you must enclose the copies in covers that carry,
clearly and legibly, all these Cover Texts: Front-Cover Texts on the front
cover, and Back-Cover Texts on the back cover. Both covers must also clearly
and legibly identify you as the publisher of these copies. The front cover must
present the full title with all words of the title equally prominent and
visible. You may add other material on the covers in addition. Copying with
changes limited to the covers, as long as they preserve the title of the
Document and satisfy these conditions, can be treated as verbatim copying in
other respects.

If the required texts for either cover are too voluminous to fit legibly, you
should put the first ones listed (as many as fit reasonably) on the actual
cover, and continue the rest onto adjacent pages.

If you publish or distribute Opaque copies of the Document numbering more than
100, you must either include a machine-readable Transparent copy along with
each Opaque copy, or state in or with each Opaque copy a computer-network
location from which the general network-using public has access to download
using public-standard network protocols a complete Transparent copy of the
Document, free of added material. If you use the latter option, you must take
reasonably prudent steps, when you begin distribution of Opaque copies in
quantity, to ensure that this Transparent copy will remain thus accessible at
the stated location until at least one year after the last time you distribute
an Opaque copy (directly or through your agents or retailers) of that edition
to the public.

It is requested, but not required, that you contact the authors of the Document
well before redistributing any large number of copies, to give them a chance to
provide you with an updated version of the Document.

=== 4. MODIFICATIONS
You may copy and distribute a Modified Version of the Document under the
conditions of sections 2 and 3 above, provided that you release the Modified
Version under precisely this License, with the Modified Version filling the
role of the Document, thus licensing distribution and modification of the
Modified Version to whoever possesses a copy of it. In addition, you must do
these things in the Modified Version:

A. Use in the Title Page (and on the covers, if any) a title distinct from that
of the Document, and from those of previous versions (which should, if there
were any, be listed in the History section of the Document). You may use the
same title as a previous version if the original publisher of that version
gives permission.

B. List on the Title Page, as authors, one or more persons or entities
responsible for authorship of the modifications in the Modified Version,
together with at least five of the principal authors of the Document (all of
its principal authors, if it has fewer than five), unless they release you from
this requirement.

C. State on the Title page the name of the publisher of the Modified Version,
as the publisher.

D. Preserve all the copyright notices of the Document.

E. Add an appropriate copyright notice for your modifications adjacent to the
other copyright notices.

F. Include, immediately after the copyright notices, a license notice giving
the public permission to use the Modified Version under the terms of this
License, in the form shown in the Addendum below.

G. Preserve in that license notice the full lists of Invariant Sections and
required Cover Texts given in the Document's license notice.

H. Include an unaltered copy of this License.

I. Preserve the section Entitled "History", Preserve its Title, and add to it
an item stating at least the title, year, new authors, and publisher of the
Modified Version as given on the Title Page. If there is no section Entitled
"History" in the Document, create one stating the title, year, authors, and
publisher of the Document as given on its Title Page, then add an item
describing the Modified Version as stated in the previous sentence.

J. Preserve the network location, if any, given in the Document for public
access to a Transparent copy of the Document, and likewise the network
locations given in the Document for previous versions it was based on. These
may be placed in the "History" section. You may omit a network location for a
work that was published at least four years before the Document itself, or if
the original publisher of the version it refers to gives permission.

K. For any section Entitled "Acknowledgements" or "Dedications", Preserve the
Title of the section, and preserve in the section all the substance and tone of
each of the contributor acknowledgements and/or dedications given therein.

L. Preserve all the Invariant Sections of the Document, unaltered in their text
and in their titles. Section numbers or the equivalent are not considered part
of the section titles.

M. Delete any section Entitled "Endorsements". Such a section may not be
included in the Modified Version.

N. Do not retitle any existing section to be Entitled "Endorsements" or to
conflict in title with any Invariant Section.

O. Preserve any Warranty Disclaimers.

If the Modified Version includes new front-matter sections or appendices that
qualify as Secondary Sections and contain no material copied from the Document,
you may at your option designate some or all of these sections as invariant. To
do this, add their titles to the list of Invariant Sections in the Modified
Version's license notice. These titles must be distinct from any other section
titles.

You may add a section Entitled "Endorsements", provided it contains nothing but
endorsements of your Modified Version by various parties—for example,
statements of peer review or that the text has been approved by an organization
as the authoritative definition of a standard.

You may add a passage of up to five words as a Front-Cover Text, and a passage
of up to 25 words as a Back-Cover Text, to the end of the list of Cover Texts
in the Modified Version. Only one passage of Front-Cover Text and one of
Back-Cover Text may be added by (or through arrangements made by) any one
entity. If the Document already includes a cover text for the same cover,
previously added by you or by arrangement made by the same entity you are
acting on behalf of, you may not add another; but you may replace the old one,
on explicit permission from the previous publisher that added the old one.

The author(s) and publisher(s) of the Document do not by this License give
permission to use their names for publicity for or to assert or imply
endorsement of any Modified Version.

=== 5. COMBINING DOCUMENTS
You may combine the Document with other documents released under this License,
under the terms defined in section 4 above for modified versions, provided that
you include in the combination all of the Invariant Sections of all of the
original documents, unmodified, and list them all as Invariant Sections of your
combined work in its license notice, and that you preserve all their Warranty
Disclaimers.

The combined work need only contain one copy of this License, and multiple
identical Invariant Sections may be replaced with a single copy. If there are
multiple Invariant Sections with the same name but different contents, make the
title of each such section unique by adding at the end of it, in parentheses,
the name of the original author or publisher of that section if known, or else
a unique number. Make the same adjustment to the section titles in the list of
Invariant Sections in the license notice of the combined work.

In the combination, you must combine any sections Entitled "History" in the
various original documents, forming one section Entitled "History"; likewise
combine any sections Entitled "Acknowledgements", and any sections Entitled
"Dedications". You must delete all sections Entitled "Endorsements".

=== 6. COLLECTIONS OF DOCUMENTS
You may make a collection consisting of the Document and other documents
released under this License, and replace the individual copies of this License
in the various documents with a single copy that is included in the collection,
provided that you follow the rules of this License for verbatim copying of each
of the documents in all other respects.

You may extract a single document from such a collection, and distribute it
individually under this License, provided you insert a copy of this License
into the extracted document, and follow this License in all other respects
regarding verbatim copying of that document.

=== 7. AGGREGATION WITH INDEPENDENT WORKS
A compilation of the Document or its derivatives with other separate and
independent documents or works, in or on a volume of a storage or distribution
medium, is called an "aggregate" if the copyright resulting from the
compilation is not used to limit the legal rights of the compilation's users
beyond what the individual works permit. When the Document is included in an
aggregate, this License does not apply to the other works in the aggregate
which are not themselves derivative works of the Document.

If the Cover Text requirement of section 3 is applicable to these copies of the
Document, then if the Document is less than one half of the entire aggregate,
the Document's Cover Texts may be placed on covers that bracket the Document
within the aggregate, or the electronic equivalent of covers if the Document is
in electronic form. Otherwise they must appear on printed covers that bracket
the whole aggregate.

=== 8. TRANSLATION
Translation is considered a kind of modification, so you may distribute
translations of the Document under the terms of section 4. Replacing Invariant
Sections with translations requires special permission from their copyright
holders, but you may include translations of some or all Invariant Sections in
addition to the original versions of these Invariant Sections. You may include
a translation of this License, and all the license notices in the Document, and
any Warranty Disclaimers, provided that you also include the original English
version of this License and the original versions of those notices and
disclaimers. In case of a disagreement between the translation and the original
version of this License or a notice or disclaimer, the original version will
prevail.

If a section in the Document is Entitled "Acknowledgements", "Dedications", or
"History", the requirement (section 4) to Preserve its Title (section 1) will
typically require changing the actual title.

=== 9. TERMINATION
You may not copy, modify, sublicense, or distribute the Document except as
expressly provided under this License. Any attempt otherwise to copy, modify,
sublicense, or distribute it is void, and will automatically terminate your
rights under this License.

However, if you cease all violation of this License, then your license from a
particular copyright holder is reinstated (a) provisionally, unless and until
the copyright holder explicitly and finally terminates your license, and (b)
permanently, if the copyright holder fails to notify you of the violation by
some reasonable means prior to 60 days after the cessation.

Moreover, your license from a particular copyright holder is reinstated
permanently if the copyright holder notifies you of the violation by some
reasonable means, this is the first time you have received notice of violation
of this License (for any work) from that copyright holder, and you cure the
violation prior to 30 days after your receipt of the notice.

Termination of your rights under this section does not terminate the licenses
of parties who have received copies or rights from you under this License. If
your rights have been terminated and not permanently reinstated, receipt of a
copy of some or all of the same material does not give you any rights to use it.

=== 10. FUTURE REVISIONS OF THIS LICENSE
The Free Software Foundation may publish new, revised versions of the GNU Free
Documentation License from time to time. Such new versions will be similar in
spirit to the present version, but may differ in detail to address new problems
or concerns. See http://www.gnu.org/copyleft/.

Each version of the License is given a distinguishing version number. If the
Document specifies that a particular numbered version of this License "or any
later version" applies to it, you have the option of following the terms and
conditions either of that specified version or of any later version that has
been published (not as a draft) by the Free Software Foundation. If the
Document does not specify a version number of this License, you may choose any
version ever published (not as a draft) by the Free Software Foundation. If the
Document specifies that a proxy can decide which future versions of this
License can be used, that proxy's public statement of acceptance of a version
permanently authorizes you to choose that version for the Document.

=== 11. RELICENSING
"Massive Multiauthor Collaboration Site" (or "MMC Site") means any World Wide
Web server that publishes copyrightable works and also provides prominent
facilities for anybody to edit those works. A public wiki that anybody can edit
is an example of such a server. A "Massive Multiauthor Collaboration" (or
"MMC") contained in the site means any set of copyrightable works thus
published on the MMC site.

"CC-BY-SA" means the Creative Commons Attribution-Share Alike 3.0 license
published by Creative Commons Corporation, a not-for-profit corporation with a
principal place of business in San Francisco, California, as well as future
copyleft versions of that license published by that same organization.

"Incorporate" means to publish or republish a Document, in whole or in part, as
part of another Document.

An MMC is "eligible for relicensing" if it is licensed under this License, and
if all works that were first published under this License somewhere other than
this MMC, and subsequently incorporated in whole or in part into the MMC, (1)
had no cover texts or invariant sections, and (2) were thus incorporated prior
to November 1, 2008.

The operator of an MMC Site may republish an MMC contained in the site under
CC-BY-SA on the same site at any time before August 1, 2009, provided the MMC
is eligible for relicensing.

